### ISSUE TITLE
latest version published to cargo out of date

### ISSUE THREAD

**Issue by AlJohri** [timvw/qv#30]
I noticed the `--profile` flag wasn't working for some reason, and then realized I was using an out of date version of `qv` installed via `cargo install qv`.

```
❯ cargo search qv
qv = "0.1.22"               # quickly view your data
```

```
❯ cargo install qv
    Updating crates.io index
     Ignored package `qv v0.1.22` is already installed, use --force to override
```

looks like the latest version https://crates.io/crates/qv/versions is 0.1.22. would it be possible to upload the history of versions to cargo?

**Comment by AlJohri** [comment]
fwiw, I also tried installing the latest version via the compiled releases and found the GLIBC version to be too high for my system:

```
cd ~/bin

version=0.4.0
filename=qv-$version-x86_64-unknown-linux-gnu-generic.tar.gz

wget https://github.com/timvw/qv/releases/download/v$version/$filename
tar -zxf $filename
rm $filename
```

```
qv --help
qv: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by qv)
qv: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by qv)
```

**Comment by AlJohri** [comment]
third time's the charm! after upgrading rustc to the latest version via rustup, I was able to install via: `cargo install --git https://github.com/timvw/qv` 🎉

(however, `qv --version` shows `0.2.0` so the version in `Cargo.toml` may be out of date)

**Comment by timvw** [comment]
The version on crates.io is outdated indeed (because  we a more recent version of delta). Will bump the version number on the main branch...

**Comment by timvw** [comment]
In order to install the desired "release" version you can run (with the version number set correctly) 
`cargo install --git https://github.com/timvw/qv --tag v0.4.0`

Updated the installation instructions.

Thank you for your feedback

**Comment by guilhem-dvr** [comment]
> The version on crates.io is outdated indeed (because we a more recent version of delta). Will bump the version number on the main branch...

Hi, I don't want to open another issue but I noticed the version on crates.io is still 0.1.22. 

Would it be possible to push the latest version?

**Comment by timvw** [comment]
Publishing binaries crates.io does not work well (eg: restricted to MB or so).

Installing the latest release is still possible as mentionned in the installation instructions

```bash
cargo install --git https://github.com/timvw/qv --tag v0.8.1
```
