### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by alippai** [timvw/qv#37]
It might be because of the high number of CPUs (if arrow starts a thread-per-core threadpool), but reading a 1MB parquet file (with limits) takes 3s.
When running `qv table.parquet` likely only one thread / CPU is needed (or one per column at most) as in theory we are reading only one batch (few rows)?!

**Comment by alippai** [comment]
Had time to check the  `strace`, the problem looks to be some network / AWS related code which runs even when I'm simply reading a single file from disk. I don't think I can control this from outside with env vars / aws settings files, maybe the config loading itself is slow?

Can we load the config only if S3 is used or can we explicitly disable GCS/AWS with an arg?

**Comment by alippai** [comment]
Also the concurrency handling is weird (but actually it might be correct, but giving feedback as it can be interesting for you). I see 300 `mmap()` calls, if the same happens for S3/GCS (but with HTTP connections without pooling and caching), that won't scale well :)

**Comment by alippai** [comment]
@timvw: should I file a PR? Which solution would you prefer?

"Can we load the config only if S3 is used or can we explicitly disable GCS/AWS with an arg?"

**Comment by timvw** [comment]
A PR would be very welcome 🙏 .

 I'd simply look at the provided path/url (and only when it starts with s3 do the aws stuff (and similar for gcs)).

Thank you!

**Comment by timvw** [comment]
I have updated the code such that the aws_sdk_config is only loaded when needed (pushed to main branch, but not released yet).

My timings indicate that this has significantly improved for cases where no s3 is touched..

**Comment by alippai** [comment]
Thanks!
I was traveling, will check it out as soon as released, the change looks good 🤞

**Comment by alippai** [comment]
The results look good. Is there an ETA for a new release?

**Comment by timvw** [comment]
The binaries (and homebrew bottles) are still being baked.. but within a couple of hours https://github.com/timvw/qv/releases/tag/v0.6.0 should be available...
