### ISSUE TITLE
Support paritioned parquet dataset

### ISSUE THREAD

**Issue by alippai** [timvw/qv#8]
File location patterns `mydata/*.parquet` and `mydata/partition=01/*.parquet` are common storage formats. Is it possible to support reading `mydata` in these cases? In theory Datafusion should have some support

**Comment by timvw** [comment]
I have asked and implemented the same globbing feature(s) in datafusion: [isue-2393](https://github.com/apache/arrow-datafusion/issues/2393), but not sure how much of that is still supported after the recent refactorings...

In my example I have the following:
* s3://bucket/events/year=2022/month=4/day=5/part-xxx.c000.snappy.parquet 
* s3://bucket/events/year=2022/month=4/day=4/part-xxx.c000.snappy.parquet
The following just works:  qv s3://bucket/events

Unfortunately, the following does not work (anymore):
qv "s3://bucket/events/year=2022/month=4/**/*.parquet"

**Comment by alippai** [comment]
Makes sense, thank you.

**Comment by timvw** [comment]
In the newest release there is now support for globbing as well :) (
eg: qv "s3://datafusion-parquet-testing/data/alltypes_pla*n.parquet" works as expected

I have also updated the "listing" of files such that hidden files/directories such as_SUCCESS/_temporary are excluded

**Comment by ianthetechie** [comment]
In case anyone finds this later via a search engine (like me :P), the "trick" is to use a [`ListingTable`](https://docs.rs/datafusion/latest/datafusion/datasource/listing/struct.ListingTable.html). You'll also need to register your S3 storage backend, which wasn't immediately intuitive, but there's an example here: https://github.com/apache/datafusion/blob/fcb193b941c19eeda7a99e69ef6610776d905193/datafusion-examples/examples/external_dependency/query-aws-s3.rs#L25.
